### ISSUE TITLE
Nothing happend. Permission denied.

### ISSUE THREAD

**Issue by luckydonald** [danielbayley/atom-plist-converter#1]
I opened `/System/Library/CoreServices/CoreTypes.bundle/Contents/Info.plist`.
Still unreadable glibberish.

**Atom Version**: 1.2.2
**System**: Mac OS X 10.9.5

Using the command `plutil -convert xml1 ${filepath}` in console:

``` shell
mac:~ luckydonald$ plutil -convert xml1 /System/Library/CoreServices/CoreTypes.bundle/Contents/Info.plist
/System/Library/CoreServices/CoreTypes.bundle/Contents/Info.plist: Permission denied
```

So, maybe using a temporary file somewhere could help?

**Comment by luckydonald** [comment]
Maybe the `-o` flag can help?  
From `plutil --help`:

``` shell
-o path                       specify alternate file path name for result;
                               the -o option is used with -convert, and is only
                               useful with one file argument (last file overwrites);
                               the path '-' means stdout
```

**Comment by danielbayley** [comment]
Same behaviour here on 10.11… I hadn't considered dealing with files that need root/sudo permissions to be honest.

> So, maybe using a temporary file somewhere could help?

Maybe. As it stands the file just gets converted in place. Doing a quick `plutil -convert xml1 -o - /System/Library/CoreServices/CoreTypes.bundle/Contents/Info.plist` from Terminal gives the correct output… It might be worth looking at replacing the text buffer with the output of this instead, but I can still see potential problems with converting back on save/close.

I'll revisit this when I get chance, unless you want to try a PR?

**Comment by luckydonald** [comment]
Or using `stdout` and `stdin` using `-` as filename for in-/output

**Comment by danielbayley** [comment]
@luckydonald The [latest](https://github.com/danielbayley/atom-plist-converter/commit/d1fb8a9f7ea3e93a9e33e24611a99a94d7f90677) update semi-addresses this, but there's still the underlying problem of how Atom handles files that need `sudo` permission. I'm not sure how/if this can be addressed within the context of this package?

**Comment by luckydonald** [comment]
Actually I have no idea. At least I can open it to read it.

**Comment by luckydonald** [comment]
Thanks :D
